spring:
  main:
    web-application-type: none
  datasource:
    mysql-one:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test
      username: root
      password: password
    mysql-batch:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-batch
      username: root
      password: password

  batch:
    jdbc:
      initialize-schema: ALWAYS
